# Generated by Django 4.0.7 on 2022-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('uid', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
